// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseControl.proto

package warehouse_CA.warehouseControl;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightOnOff = 1;</code>
   */
  java.lang.String getLightOnOff();
  /**
   * <code>string lightOnOff = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightOnOffBytes();
}
