// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseControl.proto

package warehouse_CA.warehouseControl;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomId = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string roomId = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();
}
