// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseControl.proto

package warehouse_CA.warehouseControl;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string correctTemperature = 1;</code>
   */
  java.lang.String getCorrectTemperature();
  /**
   * <code>string correctTemperature = 1;</code>
   */
  com.google.protobuf.ByteString
      getCorrectTemperatureBytes();
}
