// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseControl.proto

package warehouse_CA.warehouseControl;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.TempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currentTemperature = 1;</code>
   */
  java.lang.String getCurrentTemperature();
  /**
   * <code>string currentTemperature = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentTemperatureBytes();

  /**
   * <code>string roomId = 2;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string roomId = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();
}
