// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseControl.proto

package warehouse_CA.warehouseControl;

public final class warehouseControlImpl {
  private warehouseControlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_LightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026warehouseControl.proto\022\010service1\"9\n\013Te" +
      "mpRequest\022\032\n\022currentTemperature\030\001 \001(\t\022\016\n" +
      "\006roomId\030\002 \001(\t\"*\n\014TempResponse\022\032\n\022correct" +
      "Temperature\030\001 \001(\t\"\036\n\014LightRequest\022\016\n\006roo" +
      "mId\030\001 \001(\t\"#\n\rLightResponse\022\022\n\nlightOnOff" +
      "\030\001 \001(\t2\233\001\n\020warehouseControl\022=\n\nchangeTem" +
      "p\022\025.service1.TempRequest\032\026.service1.Temp" +
      "Response(\001\022H\n\017turnOnOffLights\022\026.service1" +
      ".LightRequest\032\027.service1.LightResponse\"\000" +
      "(\0010\001B7\n\035warehouse_CA.warehouseControlB\024w" +
      "arehouseControlImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TempRequest_descriptor,
        new java.lang.String[] { "CurrentTemperature", "RoomId", });
    internal_static_service1_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TempResponse_descriptor,
        new java.lang.String[] { "CorrectTemperature", });
    internal_static_service1_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_LightRequest_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_service1_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_LightResponse_descriptor,
        new java.lang.String[] { "LightOnOff", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
