// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automateOrders.proto

package warehouse_CA.automateOrders;

public final class automateOrdersImpl {
  private automateOrdersImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_OrderDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_OrderDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_OrderDetailsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_OrderDetailsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_OrderStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_OrderStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_OrderStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_OrderStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024automateOrders.proto\022\010service1\"-\n\023Orde" +
      "rDetailsRequest\022\026\n\016productOrdered\030\001 \001(\t\"" +
      "P\n\024OrderDetailsResponse\022\017\n\007orderId\030\001 \001(\t" +
      "\022\021\n\torderDate\030\002 \001(\t\022\024\n\014deliveryDate\030\003 \001(" +
      "\t\"%\n\022OrderStatusRequest\022\017\n\007orderId\030\001 \001(\t" +
      "\"0\n\023OrderStatusResponse\022\031\n\021orderStatusOu" +
      "tput\030\001 \001(\t\"Y\n\007Message\022&\n\006detail\030\001 \001(\0162\026." +
      "service1.Message.Enum\"&\n\004Enum\022\013\n\007UNKNOWN" +
      "\020\000\022\007\n\003LOW\020\001\022\010\n\004HIGH\020\002\"\007\n\005Empty2\352\001\n\016autom" +
      "ateOrders\022V\n\017getOrderDetails\022\035.service1." +
      "OrderDetailsRequest\032\036.service1.OrderDeta" +
      "ilsResponse\"\000(\0010\001\022Q\n\020checkOrderStatus\022\034." +
      "service1.OrderStatusRequest\032\035.service1.O" +
      "rderStatusResponse\"\000\022-\n\005empty\022\021.service1" +
      ".Message\032\017.service1.Empty\"\000B3\n\033warehouse" +
      "_CA.automateOrdersB\022automateOrdersImplP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_OrderDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_OrderDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_OrderDetailsRequest_descriptor,
        new java.lang.String[] { "ProductOrdered", });
    internal_static_service1_OrderDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_OrderDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_OrderDetailsResponse_descriptor,
        new java.lang.String[] { "OrderId", "OrderDate", "DeliveryDate", });
    internal_static_service1_OrderStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_OrderStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_OrderStatusRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_service1_OrderStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_OrderStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_OrderStatusResponse_descriptor,
        new java.lang.String[] { "OrderStatusOutput", });
    internal_static_service1_Message_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_service1_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
