// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automateOrders.proto

package warehouse_CA.automateOrders;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Empty)
    com.google.protobuf.MessageOrBuilder {
}
