// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automateOrders.proto

package warehouse_CA.automateOrders;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service1.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.service1.Message.Enum detail = 1;</code>
   */
  warehouse_CA.automateOrders.Message.Enum getDetail();
}
