// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automateOrders.proto

package warehouse_CA.automateOrders;

public interface OrderDetailsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.OrderDetailsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderId = 1;</code>
   */
  java.lang.String getOrderId();
  /**
   * <code>string orderId = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>string orderDate = 2;</code>
   */
  java.lang.String getOrderDate();
  /**
   * <code>string orderDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderDateBytes();

  /**
   * <code>string deliveryDate = 3;</code>
   */
  java.lang.String getDeliveryDate();
  /**
   * <code>string deliveryDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeliveryDateBytes();
}
