// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automateOrders.proto

package warehouse_CA.automateOrders;

public interface OrderStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.OrderStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderStatusOutput = 1;</code>
   */
  java.lang.String getOrderStatusOutput();
  /**
   * <code>string orderStatusOutput = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderStatusOutputBytes();
}
