// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automateOrders.proto

package warehouse_CA.automateOrders;

public interface OrderDetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.OrderDetailsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productOrdered = 1;</code>
   */
  java.lang.String getProductOrdered();
  /**
   * <code>string productOrdered = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductOrderedBytes();
}
