// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automateOrders.proto

package warehouse_CA.automateOrders;

public interface OrderStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.OrderStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderId = 1;</code>
   */
  java.lang.String getOrderId();
  /**
   * <code>string orderId = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
