// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manageStock.proto

package warehouse_CA.manageStock;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productConditionId = 1;</code>
   */
  java.lang.String getProductConditionId();
  /**
   * <code>string productConditionId = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductConditionIdBytes();
}
