// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manageStock.proto

package warehouse_CA.manageStock;

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productConditionOutput = 1;</code>
   */
  java.lang.String getProductConditionOutput();
  /**
   * <code>string productConditionOutput = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductConditionOutputBytes();
}
