// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manageStock.proto

package warehouse_CA.manageStock;

public final class manageStockImpl {
  private manageStockImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_WarehouseStockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_WarehouseStockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_WarehouseStockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_WarehouseStockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021manageStock.proto\022\010service1\"*\n\025Warehou" +
      "seStockRequest\022\021\n\tproductId\030\001 \001(\t\".\n\026War" +
      "ehouseStockResponse\022\024\n\014productCount\030\001 \001(" +
      "\t\")\n\013ListRequest\022\032\n\022productConditionId\030\001" +
      " \001(\t\".\n\014ListResponse\022\036\n\026productCondition" +
      "Output\030\001 \001(\t\"Y\n\007Message\022&\n\006detail\030\001 \001(\0162" +
      "\026.service1.Message.Enum\"&\n\004Enum\022\013\n\007UNKNO" +
      "WN\020\000\022\007\n\003LOW\020\001\022\010\n\004HIGH\020\002\"\007\n\005Empty2\335\001\n\013man" +
      "ageStock\022S\n\nstockCheck\022\037.service1.Wareho" +
      "useStockRequest\032 .service1.WarehouseStoc" +
      "kResponse\"\0000\001\022J\n\027productConditionChecker" +
      "\022\025.service1.ListRequest\032\026.service1.ListR" +
      "esponse\"\000\022-\n\005empty\022\021.service1.Message\032\017." +
      "service1.Empty\"\000B-\n\030warehouse_CA.manageS" +
      "tockB\017manageStockImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_WarehouseStockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_WarehouseStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_WarehouseStockRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_service1_WarehouseStockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_WarehouseStockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_WarehouseStockResponse_descriptor,
        new java.lang.String[] { "ProductCount", });
    internal_static_service1_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_ListRequest_descriptor,
        new java.lang.String[] { "ProductConditionId", });
    internal_static_service1_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_ListResponse_descriptor,
        new java.lang.String[] { "ProductConditionOutput", });
    internal_static_service1_Message_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_service1_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
