// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manageStock.proto

package warehouse_CA.manageStock;

public interface WarehouseStockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.WarehouseStockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productCount = 1;</code>
   */
  java.lang.String getProductCount();
  /**
   * <code>string productCount = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductCountBytes();
}
